name: MinigamesWithFriends
version: '1.2.0'
main: doglover.minigameswithfriends.MinigamesWithFriends
api-version: '1.21'
author: Dogloverpink
authors: [Dogloverpink, dogloverblue]

commands:
  minigames:
    description: General command for all minigames related things
    aliases:
      - mg
      - mgwf
