package doglover.minigameswithfriends.modifiers;

import doglover.minigameswithfriends.configs.modifierconfigs.AllBlocksHaveGravityConfig;
import doglover.minigameswithfriends.gamemodes.Modifier;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.block.TileState;
import org.bukkit.block.data.BlockData;
import org.bukkit.entity.FallingBlock;
import org.bukkit.entity.Item;
import org.bukkit.entity.Player;

import java.util.*;

import static doglover.minigameswithfriends.utils.BlockUtils.convertBlockToFallingBlock;

/* --AI Use Disclosure--
 * A large portion of the code in this file was generated by AI. I designed the basic flow, and 2 of the 3 optimizations, but
 * an AI model did a lot of the implementation of such functions.
 *  - DogLoverPink
 * */
public class AllBlocksHaveGravity extends Modifier {

    private static final AllBlocksHaveGravityConfig CONFIG = new AllBlocksHaveGravityConfig();

    static {
       Modifier.register("AllBlocksHaveGravity", AllBlocksHaveGravity.class, AllBlocksHaveGravity::new, CONFIG);
    }

    private static final int BLOCKS_PER_CHUNK = 16;

    private static final int TICKS_BETWEEN_SCANS = 4;

    private static final int TICKS_BETWEEN_ITEM_CLEANUPS = 20;

    /**
     * Cumulative distance (in blocks) a vanilla falling block covers after each tick of falling,
     * using vanilla physics: velocity = (velocity + 0.04) * 0.98 per tick. Culled blocks land on
     * the tick their entity equivalent would have, so a fall finishes at the same moment whether
     * or not it was ever drawn.
     */
    private static final double[] FALL_DISTANCE_BY_TICK = new double[320];

    static {
        double velocity = 0;
        double distance = 0;
        for (int tick = 0; tick < FALL_DISTANCE_BY_TICK.length; tick++) {
            velocity = (velocity + 0.04) * 0.98;
            distance += velocity;
            FALL_DISTANCE_BY_TICK[tick] = distance;
        }
    }

    private static final BlockFace[] FACES = {
            BlockFace.UP, BlockFace.DOWN, BlockFace.NORTH, BlockFace.SOUTH, BlockFace.EAST, BlockFace.WEST
    };

    private record BlockPos(int x, int y, int z) {

        BlockPos relative(BlockFace face) {
            return new BlockPos(x + face.getModX(), y + face.getModY(), z + face.getModZ());
        }
    }

    private record ColumnPos(int x, int z) {
    }

    /**
     * A block falling with no entity to represent it: it has already been removed from the world,
     * and is placed at (x, y, z) once the server reaches landTick.
     */
    private record PendingFall(World world, int x, int y, int z, BlockData data, int landTick) {
    }

    private final List<PendingFall> pendingFalls = new ArrayList<>();

    /**
     * The highest Y already claimed by an in-flight fall in each column. A culled fall removes its
     * block from the world the instant it starts, so the world alone can't tell us where the ground
     * will be by the time a later block arrives; without this, two falls aim at the same spot.
     */
    private final Map<ColumnPos, Integer> claimedLandings = new HashMap<>();

    /** Live falling blocks that may be retired this sweep, furthest from any player first. */
    private final Queue<FallingBlock> evictionCandidates = new ArrayDeque<>();

    private int ticksSinceLastScan;
    private int ticksSinceItemCleanup;
    private int fallingEntityBudget;

    private int horizontalScanRadius;
    private int verticalScanRadius;
    private boolean cullInvisibleBlocks;
    private double maxVisibilityDistanceSquared;
    private double alwaysVisibleRadiusSquared;
    private int maxFallingBlockEntities;
    private int maxDroppedItemsPerWorld;
    private boolean applyPhysicsUpdates;

    public AllBlocksHaveGravity() {
    }

    @Override
    public AllBlocksHaveGravityConfig getConfig() {
        return CONFIG;
    }

    @Override
    public void onGameStart() {
        updateConfig();
        ticksSinceLastScan = 0;
        ticksSinceItemCleanup = 0;
    }

    @Override
    public void onGameEnd() {
        //Land everything instantly so no blocks are lost if the game stops mid-fall
        for (PendingFall fall : pendingFalls) {
            land(fall);
        }
        pendingFalls.clear();
        claimedLandings.clear();
        evictionCandidates.clear();
    }

    @Override
    public void updateConfig() {
        AllBlocksHaveGravityConfig config = getConfig();
        horizontalScanRadius = config.getHorizontalEffectRadius();
        verticalScanRadius = config.getVerticalEffectRadius();
        cullInvisibleBlocks = config.isInvisibleBlockCullingEnabled();

        double maxVisibility = config.getMaxBlockVisibilityDistanceBlocks();
        maxVisibilityDistanceSquared = maxVisibility * maxVisibility;
        double alwaysVisible = config.getAlwaysVisibleRadiusBlocks();
        alwaysVisibleRadiusSquared = alwaysVisible * alwaysVisible;

        maxFallingBlockEntities = config.getMaxConcurrentFallingBlockEntities();
        maxDroppedItemsPerWorld = config.getMaxDroppedItemsPerWorld();
        applyPhysicsUpdates = config.shouldApplyPhysicsUpdatesToFallingBlocks();
    }

    @Override
    public void tick() {
        landDuePendingFalls();

        ticksSinceItemCleanup++;
        if (ticksSinceItemCleanup >= TICKS_BETWEEN_ITEM_CLEANUPS) {
            ticksSinceItemCleanup = 0;
            removeExcessDroppedItems();
        }

        ticksSinceLastScan++;
        if (ticksSinceLastScan < TICKS_BETWEEN_SCANS) {
            return;
        }
        ticksSinceLastScan = 0;

        List<Player> viewers = new ArrayList<>(getGame().getPlayers());

        rebuildClaimedLandings();
        prepareEntityBudget(viewers);
        for (Player player : viewers) {
            collapseAround(player.getLocation(), viewers);
        }
        evictionCandidates.clear();
    }

    private void collapseAround(Location center, List<Player> viewers) {
        World world = center.getWorld();
        if (world == null) {
            return;
        }

        int centerX = center.getBlockX();
        int centerY = center.getBlockY();
        int centerZ = center.getBlockZ();

        int minY = Math.max(world.getMinHeight() + 1, centerY - verticalScanRadius);
        int maxY = Math.min(world.getMaxHeight() - 1, centerY + verticalScanRadius);

        //find every block that is going to fall, grouped into vertical columns, WITHOUT
        //mutating the world yet. The full set is needed first so the visibility pass can treat
        //falling neighbours as still occluding (a buried block stays hidden while the blocks
        //around it fall alongside it).
        Set<BlockPos> fallingPositions = new HashSet<>();
        List<List<Block>> columns = new ArrayList<>();

        for (int x = centerX - horizontalScanRadius; x <= centerX + horizontalScanRadius; x++) {
            for (int z = centerZ - horizontalScanRadius; z <= centerZ + horizontalScanRadius; z++) {
                if (!isChunkLoaded(world, x, z)) {
                    continue;
                }
                List<Block> column = null;
                boolean belowVacated = false;
                for (int y = minY; y <= maxY; y++) {
                    Block block = world.getBlockAt(x, y, z);
                    boolean bottomFree = belowVacated || !block.getRelative(BlockFace.DOWN).getType().isSolid();
                    if (bottomFree && canFall(block)) {
                        if (column == null) {
                            column = new ArrayList<>();
                        }
                        column.add(block);
                        if (cullInvisibleBlocks) {
                            fallingPositions.add(new BlockPos(x, y, z));
                        }
                        belowVacated = true;
                    } else {
                        belowVacated = false;
                    }
                }
                if (column != null) {
                    columns.add(column);
                }
            }
        }

        for (List<Block> column : columns) {
            processColumn(world, column, fallingPositions, viewers);
        }
    }

    /**
     * Every falling block in a column is assigned its landing slot up front (they stack in order
     * on whatever solid ground is below), so falls in the same column can't fight over the same
     * resting spot.
     */
    private void processColumn(World world, List<Block> column, Set<BlockPos> fallingPositions, List<Player> viewers) {
        Block lowest = column.getFirst();
        int x = lowest.getX();
        int z = lowest.getZ();

        int minHeight = world.getMinHeight();
        int groundY = lowest.getY() - 1;
        while (groundY >= minHeight && !world.getBlockAt(x, groundY, z).getType().isSolid()) {
            groundY--;
        }
        //No solid ground all the way down means the column falls into the void
        boolean landsInVoid = groundY < minHeight;

        //Stack on top of whatever is already falling into this column, not just on the visible ground
        ColumnPos columnKey = new ColumnPos(x, z);
        int landY = groundY + 1;
        Integer claimedTop = claimedLandings.get(columnKey);
        if (claimedTop != null && claimedTop >= landY) {
            landY = claimedTop + 1;
        }

        int now = Bukkit.getCurrentTick();
        for (Block block : column) {
            BlockPos pos = new BlockPos(block.getX(), block.getY(), block.getZ());

            if (landsInVoid) {
                if (wantsEntity(world, pos, fallingPositions, viewers)) {
                    convertBlockToFallingBlock(block, applyPhysicsUpdates);
                } else {
                    clearBlock(block);
                }
                landY++;
                continue;
            }

            int fallDistance = block.getY() - landY;
            if (fallDistance <= 0) {
                landY = block.getY() + 1;
                continue;
            }

            if (wantsEntity(world, pos, fallingPositions, viewers)) {
                convertBlockToFallingBlock(block, applyPhysicsUpdates);
            } else {
                BlockData data = block.getBlockData();
                clearBlock(block);
                pendingFalls.add(new PendingFall(world, x, landY, z, data, now + fallTicks(fallDistance)));
            }
            landY++;
        }
        claimedLandings.merge(columnKey, landY - 1, Math::max);
    }

    /**
     * Whether this block deserves to actually have falling block be rendered
     */
    private boolean wantsEntity(World world, BlockPos pos, Set<BlockPos> fallingPositions, List<Player> viewers) {
        if (!isWorthDrawing(world, pos, fallingPositions, viewers)) {
            return false;
        }
        if (fallingEntityBudget <= 0) {
            return retireFallingBlockFurtherThan(world, pos, viewers);
        }
        fallingEntityBudget--;
        return true;
    }

    private boolean isWorthDrawing(World world, BlockPos pos, Set<BlockPos> fallingPositions, List<Player> viewers) {
        if (!cullInvisibleBlocks) {
            return true;
        }
        List<BlockFace> exposedFaces = getExposedFaces(world, pos, fallingPositions);
        if (exposedFaces.isEmpty()) {
            return false;
        }
        return isSeenByAnyPlayer(world, pos, exposedFaces, viewers);
    }

    private List<BlockFace> getExposedFaces(World world, BlockPos pos, Set<BlockPos> fallingPositions) {
        List<BlockFace> exposed = new ArrayList<>(FACES.length);
        for (BlockFace face : FACES) {
            BlockPos neighbour = pos.relative(face);
            if (fallingPositions.contains(neighbour)) {
                continue;
            }
            if (!isChunkLoaded(world, neighbour.x(), neighbour.z())) {
                continue;
            }
            if (!world.getBlockAt(neighbour.x(), neighbour.y(), neighbour.z()).getType().isOccluding()) {
                exposed.add(face);
            }
        }
        return exposed;
    }

    private boolean isSeenByAnyPlayer(World world, BlockPos pos, List<BlockFace> exposedFaces, List<Player> viewers) {
        double centreX = pos.x() + 0.5;
        double centreY = pos.y() + 0.5;
        double centreZ = pos.z() + 0.5;

        for (Player player : viewers) {
            if (!world.equals(player.getWorld())) {
                continue;
            }
            Location eye = player.getEyeLocation();
            double toEyeX = eye.getX() - centreX;
            double toEyeY = eye.getY() - centreY;
            double toEyeZ = eye.getZ() - centreZ;

            double distanceSquared = (toEyeX * toEyeX) + (toEyeY * toEyeY) + (toEyeZ * toEyeZ);
            if (distanceSquared > maxVisibilityDistanceSquared) {
                continue;
            }
            //If it's too close to a player, always render it cause otherwise it looks bad in some cases
            if (distanceSquared <= alwaysVisibleRadiusSquared) {
                return true;
            }

            BlockFace facing = faceMostTurnedTowards(exposedFaces, toEyeX, toEyeY, toEyeZ);
            Location target = new Location(world,
                    centreX + facing.getModX(),
                    centreY + facing.getModY(),
                    centreZ + facing.getModZ());
            if (player.hasLineOfSight(target)) {
                return true;
            }
        }
        return false;
    }

    private static BlockFace faceMostTurnedTowards(List<BlockFace> faces, double toEyeX, double toEyeY, double toEyeZ) {
        BlockFace best = faces.getFirst();
        double bestDot = -Double.MAX_VALUE;
        for (BlockFace face : faces) {
            double dot = (face.getModX() * toEyeX) + (face.getModY() * toEyeY) + (face.getModZ() * toEyeZ);
            if (dot > bestDot) {
                bestDot = dot;
                best = face;
            }
        }
        return best;
    }

    /**
     * Works out how many falling block entities may still be spawned this sweep, and lines up the
     * ones that could be retired to make room. Both are counted from the world rather than tracked
     * across ticks, so they can't drift as entities land.
     */
    private void prepareEntityBudget(List<Player> viewers) {
        evictionCandidates.clear();
        if (maxFallingBlockEntities <= 0) {
            fallingEntityBudget = Integer.MAX_VALUE;
            return;
        }

        Set<World> worlds = new HashSet<>();
        for (Player player : viewers) {
            worlds.add(player.getWorld());
        }
        List<FallingBlock> alive = new ArrayList<>();
        for (World world : worlds) {
            alive.addAll(world.getEntitiesByClass(FallingBlock.class));
        }
        fallingEntityBudget = Math.max(0, maxFallingBlockEntities - alive.size());

        if (fallingEntityBudget > 0) {
            return;
        }

        //Cull far away blocks first, so closest blocks still render to the player
        List<FallingBlock> candidates = new ArrayList<>(alive.size());
        for (FallingBlock entity : alive) {
            if (nearestPlayerDistanceSquared(entity, viewers) > alwaysVisibleRadiusSquared) {
                candidates.add(entity);
            }
        }
        candidates.sort(Comparator.comparingDouble(
                (FallingBlock entity) -> nearestPlayerDistanceSquared(entity, viewers)).reversed());
        evictionCandidates.addAll(candidates);
    }

    private static double nearestPlayerDistanceSquared(FallingBlock entity, List<Player> viewers) {
        Location loc = entity.getLocation();
        return nearestPlayerDistanceSquared(entity.getWorld(), loc.getX(), loc.getY(), loc.getZ(), viewers);
    }

    private static double nearestPlayerDistanceSquared(World world, double x, double y, double z, List<Player> viewers) {
        double nearest = Double.MAX_VALUE;
        for (Player player : viewers) {
            if (!player.getWorld().equals(world)) {
                continue;
            }
            Location eye = player.getEyeLocation();
            double dx = eye.getX() - x;
            double dy = eye.getY() - y;
            double dz = eye.getZ() - z;
            nearest = Math.min(nearest, (dx * dx) + (dy * dy) + (dz * dz));
        }
        return nearest;
    }

    /**
     * Culls the furthest remaining falling block so its slot can be reused by the block at the
     * given position. This won't fully delete the block but instead manually calculate where it
     * will land, just like the other optimizations.
     * <p>
     * The swap only happens if the block being retired is further from every player than the one
     * taking its place. Otherwise the trade would make things look worse rather than better, by
     * dropping something near somebody in order to draw something further away.
     *
     * @return true if a slot was actually freed.
     */
    private boolean retireFallingBlockFurtherThan(World world, BlockPos pos, List<Player> viewers) {
        double newBlockDistanceSquared = nearestPlayerDistanceSquared(
                world, pos.x() + 0.5, pos.y() + 0.5, pos.z() + 0.5, viewers);

        while (!evictionCandidates.isEmpty()) {
            FallingBlock candidate = evictionCandidates.peek();
            if (!candidate.isValid()) {
                evictionCandidates.poll();
                continue;
            }
            //Candidates are queued furthest first, so once the head is nearer than this block,
            //nothing left in the queue is worth trading away either.
            if (nearestPlayerDistanceSquared(candidate, viewers) <= newBlockDistanceSquared) {
                return false;
            }
            evictionCandidates.poll();
            if (convertToPendingFall(candidate)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Replaces a live falling block entity with an invisible fall that lands identically. Returns
     * false if it's too close to landing to be worth taking over, in which case it is left alone.
     */
    private boolean convertToPendingFall(FallingBlock entity) {
        World world = entity.getWorld();
        Location loc = entity.getLocation();
        int x = loc.getBlockX();
        int z = loc.getBlockZ();
        int currentY = loc.getBlockY();

        int minHeight = world.getMinHeight();
        int groundY = currentY - 1;
        while (groundY >= minHeight && !world.getBlockAt(x, groundY, z).getType().isSolid()) {
            groundY--;
        }
        if (groundY < minHeight) {
            //Falling into the void: nothing will ever land, so the entity is pure cost
            entity.remove();
            return true;
        }

        ColumnPos columnKey = new ColumnPos(x, z);
        int landY = groundY + 1;
        Integer claimedTop = claimedLandings.get(columnKey);
        if (claimedTop != null && claimedTop >= landY) {
            landY = claimedTop + 1;
        }

        int remaining = currentY - landY;
        if (remaining <= 0) {
            return false;
        }

        int landTick = Bukkit.getCurrentTick() + remainingFallTicks(entity.getTicksLived(), remaining);
        pendingFalls.add(new PendingFall(world, x, landY, z, entity.getBlockData(), landTick));
        claimedLandings.merge(columnKey, landY, Math::max);
        entity.remove();
        return true;
    }

    /**
     * Purges excessive item entities on the ground
     */
    private void removeExcessDroppedItems() {
        if (maxDroppedItemsPerWorld <= 0) {
            return;
        }
        Set<World> worlds = new HashSet<>();
        for (Player player : getGame().getPlayers()) {
            worlds.add(player.getWorld());
        }

        for (World world : worlds) {
            List<Item> items = new ArrayList<>(world.getEntitiesByClass(Item.class));
            int excess = items.size() - maxDroppedItemsPerWorld;
            if (excess <= 0) {
                continue;
            }
            items.sort(Comparator.comparingInt(Item::getTicksLived).reversed());
            for (Item item : items) {
                if (excess <= 0) {
                    break;
                }
                if (!item.getItemStack().getType().isBlock()) {
                    continue;
                }
                item.remove();
                excess--;
            }
        }
    }

    /**
     * Recomputes, from the falls currently in flight, the highest landing spot claimed in each
     * column. Rebuilt from scratch each sweep so it can never drift out of sync with reality.
     */
    private void rebuildClaimedLandings() {
        claimedLandings.clear();
        for (PendingFall fall : pendingFalls) {
            claimedLandings.merge(new ColumnPos(fall.x(), fall.z()), fall.y(), Math::max);
        }
    }

    private void landDuePendingFalls() {
        if (pendingFalls.isEmpty()) {
            return;
        }
        int now = Bukkit.getCurrentTick();
        pendingFalls.removeIf(fall -> {
            if (fall.landTick() > now) {
                return false;
            }
            land(fall);
            return true;
        });
    }

    private void land(PendingFall fall) {
        World world = fall.world();
        int y = fall.y();
        int maxY = world.getMaxHeight() - 1;
        while (y <= maxY && world.getBlockAt(fall.x(), y, fall.z()).getType().isSolid()) {
            y++;
        }
        if (y > maxY) {
            return;
        }
        world.getBlockAt(fall.x(), y, fall.z()).setBlockData(fall.data(), applyPhysicsUpdates);
    }

    private boolean canFall(Block block) {
        Material type = block.getType();

        if (type.isAir() || type == Material.WATER || type == Material.LAVA) {
            return false;
        }
        if (type.getHardness() == -1) {
            return false;
        }
        //Don't make things like chests fall cause they would lose their data
        return !(block.getState(false) instanceof TileState);
    }

    private void clearBlock(Block block) {
        block.setType(Material.AIR, applyPhysicsUpdates);
    }

    /**
     * How far a block has dropped after falling for this many ticks.
     */
    private static double distanceFallenAfter(int ticks) {
        if (ticks <= 0) {
            return 0;
        }
        return FALL_DISTANCE_BY_TICK[Math.min(ticks, FALL_DISTANCE_BY_TICK.length) - 1];
    }

    /**
     * How many more ticks a block that has already been falling for ticksFallen needs in order to
     * land
     * */
    private static int remainingFallTicks(int ticksFallen, int remainingBlocks) {
        double target = distanceFallenAfter(ticksFallen) + remainingBlocks;
        for (int tick = Math.max(0, ticksFallen); tick < FALL_DISTANCE_BY_TICK.length; tick++) {
            if (FALL_DISTANCE_BY_TICK[tick] >= target) {
                return Math.max(1, (tick + 1) - ticksFallen);
            }
        }
        return Math.max(1, FALL_DISTANCE_BY_TICK.length - ticksFallen);
    }

    /**
     * How many ticks a falling block takes to cover the given distance from a standing start.
     */
    private static int fallTicks(int blocks) {
        for (int tick = 0; tick < FALL_DISTANCE_BY_TICK.length; tick++) {
            if (FALL_DISTANCE_BY_TICK[tick] >= blocks) {
                return tick + 1;
            }
        }
        return FALL_DISTANCE_BY_TICK.length;
    }

    private static boolean isChunkLoaded(World world, int blockX, int blockZ) {
        return world.isChunkLoaded(Math.floorDiv(blockX, BLOCKS_PER_CHUNK), Math.floorDiv(blockZ, BLOCKS_PER_CHUNK));
    }

    @Override
    public String toString() {
        return "AllBlocksHaveGravity";
    }
}
